### ISSUE TITLE
Rename does not work

### ISSUE THREAD

**Issue by rfjakob** [airnandez/cluefs#3] opened 2015-09-07 19:00 UTC
Renaming a file leaves the renamed file in a broken state that is only fixed by unmounting and mounting again:

```
$ echo foo > foo.txt
$ ls -l
-rw-rw-r--. 1 jakob jakob 4  7. Sep 20:58 foo.txt
$ mv foo.txt bar.txt
$ ls -l
----------. 0 root root 0  1. Jan 1970  bar.txt
$ rm bar.txt
rm: cannot remove ‘bar.txt’: Input/output error
```

**Comment by airnandez** [comment] 2015-09-09 08:29
Thanks for this report. I managed to reproduce it in Ubuntu, but not on MacOS X. From what I have observed, the file is correctly renamed in the shadow directory but its metadata attributes are incorrectly exposed by clueFS after the rename operation.

I think I have a reasonably good idea of where the problem is and am working on fixing it.

**Comment by rfjakob** [comment] 2015-09-09 09:02
As I understand it, the kernel gets node ids from `Lookup()`. `bazil.org/fuse` saves those node ids for later access. The kernel knows that the node id does not change when it renames a file. So the next `stat()` goes to the same old `bazil.org/fuse` node.

The problem is that the rename operates on the parent directory and not on the file node. So you'd have to somehow find the affected file node and change `file.name` there.

This problem is solved in `go-fuse` in the `pathfs` layer, see https://github.com/hanwen/go-fuse/blob/master/fuse/pathfs/pathfs.go

**Comment by rfjakob** [comment] 2015-09-09 09:05
That it works on OSX is probably because the FUSE module in the OSX kernel is more basic and does not remember the node id when you rename the file.

Edit: `go-fuse` has a fully working loopback example: https://github.com/hanwen/go-fuse/tree/master/example/loopback

**Comment by airnandez** [comment] 2015-09-17 09:53
Fixed in master. No release yet since I want to add other modifications before tagging a new release.

Thanks for having reported this problem.

**Closed as completed by airnandez** 2015-09-17 09:53 UTC
Labels: bug
